# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.3
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.1.0+mc1.21.10
maven_group=cuspymd.mcp.mod
archives_base_name=mcp-server-mod

# Dependencies
fabric_version=0.135.0+1.21.10

# NeoForge Properties
neogradle_version=7.1.38
neoforge_minecraft_version=1.21.1
neoforge_minecraft_version_range=[1.21.1]
neoforge_version=21.1.233
neoforge_loader_version_range=[1,)
neoforge_mod_id=mcp_server_mod
neoforge_mod_name=MCP Server Mod
neoforge_mod_version=1.1.0+neoforge.mc1.21.1
